English_Ekb/English_Ekb/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = i18n_patterns(
    path("admin/", admin.site.urls),
    path('', include('school.urls', namespace='home')),
    path('teachers/', include('school.urls', namespace='teachers')),
    path('user/', include('user.urls', namespace='user')),
)


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

English_Ekb/school/urls.py
from django.urls import path

from .views import index, teachers


app_name = 'school'


urlpatterns = [
    path('', index, name='index'),
    path('teachers', teachers, name='teachers')
]

English_Ekb/user/urls.py
from django.urls import path

from .views import *


app_name = 'user'


urlpatterns = [
    path('account/', UserProfileView.as_view(), name='profile'),
    path('login/', LoginUserView.as_view(), name='login'),
    path('login/<str:email>', ConfirmMailView.as_view(), name='login-confirm'),
    path('registration/', RegistrationUserView.as_view(), name='registration'),
    path('registration/<str:email>', ConfirmMailView.as_view(), name='registration-confirm'),
    path('schedule/', ScheduleView.as_view(), name='schedule')
]

English_Ekb/school/views.py
from django.conf import settings
from django.core.mail import send_mail
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render


def index(request: HttpRequest) -> HttpResponse:
    """
    Функция представления для главной страницы.

    :param request: Объект класса HttpRequest.

    :return: Объект класса HttpResponse.
    """

    return render(request, 'school/pages/home.html')


def teachers(request: HttpRequest) -> HttpResponse:
    """ Функция представления для страницы преподавателей.

    :param request: Объект класса HttpRequest.

    :return: Объект класса HttpResponse.
    """

    return render(request, 'school/pages/teachers.html')

English_Ekb/school/views/about_school.py
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render


def index(request: HttpRequest) -> HttpResponse:
    """
    Функция представления для главной страницы.

    :param request: Объект класса HttpRequest.

    :return: Объект класса HttpResponse.
    """

    return render(request, 'school/pages/home.html')


def teachers(request: HttpRequest) -> HttpResponse:
    """ Функция представления для страницы преподавателей.

    :param request: Объект класса HttpRequest.

    :return: Объект класса HttpResponse.
    """

    return render(request, 'school/pages/teachers.html')

English_Ekb/templates/school/components/footer.html
{% load static %}


<div class="the-footer">
    <div class="footer-content">
        <div class="footer-info">
            <img class="logo-dark" src="{% static 'media/logo/logo-dark.svg' %}" alt="logo-dark.svg"/>

            <div class="footer-contacts">
                <div class="menu-contacts">
                    <nav>
                        <ul>
                            <li><a class="link-to-contacts" href="#">Контакты</a></li>
                            <li><a class="link-to-details" href="#">Реквизиты</a></li>
                        </ul>
                    </nav>
                </div>

                <div class="icons-links">
                    <div class="icons">
                        <img src="{% static 'media/icons/vk-icon-dark.svg' %}" alt="icon-vk.svg"/>
                        <img src="{% static 'media/icons/telegram-icon-dark.svg' %}" alt="icon-telegram.svg"/>
                        <img src="{% static 'media/icons/whatsapp-icon-dark.svg' %}" alt="icon-whatsapp.svg"/>
                    </div>
                </div>
            </div>
        </div>

        <div class="footer-company">
            <p>© 2024 SchoolSpeakEng</p>
        </div>
    </div>
</div>

English_Ekb/templates/school/components/header.html
{% load static %}


<div class="the-header">
    <div class="header-content">
        <div class="header-navigation">
            <img class="logo-main" src="{% static 'media/logo/logo-main.svg' %}" alt="logo-header.svg"/>

            <nav>
                <ul class="header-menu">
                    <li><a class="link-to-home" href="{% url 'school:index' %}">О школе</a></li>
                    <li><a class="link-to-lessons" href="#">Уроки</a></li>
                </ul>
            </nav>
        </div>

        <div class="header-account">
            <div class="header-icons">
                <a><img src="{% static 'media/icons/vk-icon.svg' %}" alt="vk-icon.svg"/></a>
                <a><img src="{% static 'media/icons/telegram-icon.svg' %}" alt="telegram-icon.svg"/></a>
            </div>

            <div class="account-buttons">
                <div class="account-entrance">
                    <a href="{% url 'user:login' %}">Вход</a>
                </div>

                <div class="account-registration">
                    <a href="{% url 'user:registration' %}">Регистрация</a>
                </div>
            </div>
        </div>
    </div>
</div>