English_Ekb/English_Ekb/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = i18n_patterns(
    path("admin/", admin.site.urls),
    path('', include('school.urls', namespace='home')),
    path('teachers/', include('school.urls', namespace='teachers')),
    path('user/', include('user.urls', namespace='user')),
)


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

English_Ekb/user/urls.py
from django.urls import path

from .views import *


app_name = 'user'


urlpatterns = [
    path('account/', UserProfileView.as_view(), name='profile'),
    path('login/', LoginUserView.as_view(), name='login'),
    path('login/<str:email>', ConfirmMailView.as_view(), name='login-confirm'),
    path('registration/', RegistrationUserView.as_view(), name='registration'),
    path('registration/<str:email>', ConfirmMailView.as_view(), name='registration-confirm'),
    path('schedule/', ScheduleView.as_view(), name='schedule')
]

English_Ekb/user/models.py
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.db.models import CharField, EmailField, BooleanField


class CustomUserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError('The Email field must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        return self.create_user(email, password, **extra_fields)


class CustomUser(AbstractBaseUser, PermissionsMixin):
    first_name = CharField(verbose_name='Имя')
    last_name = CharField(verbose_name='Фамилия')
    patronymic = CharField(verbose_name='Отчество', blank=True)

    password = CharField(max_length=120, verbose_name='Пароль от аккаунта')
    email = EmailField(verbose_name='Электронная почта', unique=True)
    phone = CharField(verbose_name='Номер телефона', blank=True)

    is_active = BooleanField(default=True)
    is_staff = BooleanField(default=False)
    is_superuser = BooleanField(default=False)

    objects = CustomUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        db_table_comment = 'Table with users.'
        db_table = 'users'
        verbose_name = 'пользователь'
        verbose_name_plural = 'пользователи'

    def __str__(self):
        return self.email

English_Ekb/user/models/lessons.py
from django.db.models import Model, CharField, ForeignKey, CASCADE, ManyToManyField
from .users import CustomUserModel


class Lessons(Model):
    DAYS = [
        ('Monday', 'Понедельник'),
        ('Tuesday', 'Вторник'),
        ('Wednesday', 'Среда'),
        ('Thursday', 'Четверг'),
        ('Friday', 'Пятница'),
        ('Saturday', 'Суббота'),
        ('Sunday', 'Воскресенье')
    ]

    topic = CharField(verbose_name='Тема урока', blank=True)
    users = ManyToManyField(CustomUserModel, verbose_name='Ученики', related_name='students_profile')
    teacher = ForeignKey(CustomUserModel, on_delete=CASCADE, verbose_name='Предподаватель', related_name='teacher_profile')
    link = CharField(verbose_name='Ссылка на урок', blank=True)

    day_of_week = CharField(
        choices=DAYS,
        verbose_name='День недели'
    )

    class Meta:
        db_table_comment = 'Table with lessons.'
        db_table = 'lessons'
        verbose_name = 'Урок'
        verbose_name_plural = 'Уроки'

    def __str__(self) -> str:
        return self.topic

English_Ekb/user/models/roles.py
from django.db.models import Model, CharField, ForeignKey, CASCADE
from .users import CustomUserModel


class Student(Model):
    user = ForeignKey(CustomUserModel, on_delete=CASCADE)
    teacher = CharField(max_length=25, verbose_name='ФИО предподавателя')

    class Meta:
        db_table_comment = 'Table with student role.'
        db_table = 'students'
        verbose_name = 'Студент'
        verbose_name_plural = 'Студенты'

    def __str__(self) -> str:
        return self.teacher


class Teacher(Model):
    user = ForeignKey(CustomUserModel, on_delete=CASCADE)
    experience = CharField(verbose_name='Опыт предподавателя')

    class Meta:
        db_table_comment = 'Table with teachers.'
        db_table = 'teachers'
        verbose_name = 'предподаватель'
        verbose_name_plural = 'предподаватели'

    def __str__(self) -> str:
        return self.experience

English_Ekb/user/models/user.py
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.db.models import CharField, EmailField, BooleanField, ForeignKey

from ..managers.manager_user import UserManager


class User(AbstractBaseUser):
    first_name = CharField(verbose_name='Имя')
    last_name = CharField(verbose_name='Фамилия')
    patronymic = CharField(verbose_name='Отчество', blank=True)
    role = ForeignKey()
    password = CharField(max_length=15, verbose_name='Пароль от аккаунта')
    mail = EmailField(verbose_name='Электронная почта', unique=True)
    phone = CharField(verbose_name='Номер телефона', blank=True)

    is_active = BooleanField(default=True)
    is_staff = BooleanField(default=False)

    USERNAME_FIELD = 'mail'
    REQUIRED_FIELDS = ['first_name', 'last_name', 'patronymic', 'phone']

    objects = UserManager()

    class Meta:
        db_table_comment = 'Table with users.'
        db_table = 'users'
        verbose_name = 'пользователь'
        verbose_name_plural = 'пользователи'

    def __str__(self):
        return self.mail

English_Ekb/user/models/users.py
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.db.models import CharField, EmailField, BooleanField

from ..managers.user_manager import CustomUserManager


class CustomUserModel(AbstractBaseUser, PermissionsMixin):
    ROLE = [
        ('Teacher', 'Предподаватель'),
        ('Student', 'Студент')
    ]

    first_name = CharField(verbose_name='Имя')
    last_name = CharField(verbose_name='Фамилия')
    patronymic = CharField(verbose_name='Отчество', blank=True)

    password = CharField(max_length=120, verbose_name='Пароль от аккаунта')
    email = EmailField(verbose_name='Электронная почта', unique=True)
    phone = CharField(verbose_name='Номер телефона', blank=True)

    code_from_mail = CharField(verbose_name='Код, отправленный по почту', blank=True)

    is_active = BooleanField(default=True)
    is_staff = BooleanField(default=False)
    is_superuser = BooleanField(default=False)

    role = CharField(choices=ROLE, verbose_name='Роль пользователя', blank=True)

    objects = CustomUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        db_table_comment = 'Table with users.'
        db_table = 'users'
        verbose_name = 'пользователь'
        verbose_name_plural = 'пользователи'

    def __str__(self):
        return self.email

English_Ekb/user/forms.py
from django.forms import PasswordInput, CharField
from django.contrib.auth.forms import AuthenticationForm

from .models import CustomUser


class LoginUserForm(AuthenticationForm):
    password = CharField(
        max_length=15,
        label='password',
        widget=PasswordInput(attrs={
            'class': 'form-control',
            'placeholder': 'Пароль'
        })
    )

    class Meta:
        model = CustomUser
        fields = ['password']

English_Ekb/user/forms/form_confirm.py
from django.forms import Form, CharField


class ConfirmationCodeForm(Form):
    code = CharField(max_length=6, label='Код подтверждения')

English_Ekb/user/forms/form_login.py
from django.forms import PasswordInput, CharField
from django.contrib.auth.forms import AuthenticationForm

from ..models.users import CustomUserModel


class LoginUserForm(AuthenticationForm):
    password = CharField(
        max_length=15,
        label='password',
        widget=PasswordInput(attrs={
            'class': 'form-control',
            'placeholder': 'Пароль'
        })
    )

    class Meta:
        model = CustomUserModel
        fields = ['password']

English_Ekb/user/forms/form_registration.py
from django.forms import EmailInput, EmailField
from django.contrib.auth.forms import BaseUserCreationForm

from ..models.users import CustomUserModel


class RegistrationUserForm(BaseUserCreationForm):
    email = EmailField(
         label='email',
         widget=EmailInput(attrs={
             'class': 'form-control',
             'placeholder': 'Электронная почта'
         })
    )

    class Meta:
        model = CustomUserModel
        fields = ['email']

English_Ekb/user/views/view_login.py
from django.contrib.auth.views import LoginView
from django.urls import reverse_lazy
from django.shortcuts import redirect
from django.http import HttpRequest, HttpResponse
from ..forms import LoginUserForm


class LoginUserView(LoginView):
    authentication_form = LoginUserForm
    template_name = 'user/pages/login.html'
    extra_context = {'title': 'Вход в личный кабинет'}

    email: str | None = None

    def dispatch(self, request: HttpRequest, *args, **kwargs) -> HttpResponse:
        if self.request.user:
            return redirect('user:profile')

        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form: LoginUserForm) -> HttpResponse:
        self.email = form.cleaned_data.get('username')

        return super().form_valid(form)

    def get_success_url(self) -> str:
        return reverse_lazy('user:login-confirm', kwargs={'email': self.email})

English_Ekb/user/views/view_mail.py
from typing import Any

from django.http import Http404, HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic.edit import FormView

from rest_framework_simplejwt.tokens import RefreshToken

from ..forms import ConfirmationCodeForm
from ..models import CustomUserModel


class ConfirmMailView(FormView):
    form_class = ConfirmationCodeForm

    template_name = 'user/pages/mail.html'
    extra_context = {'title': 'Подтверждение почты'}

    def form_valid(self, form: ConfirmationCodeForm) -> HttpResponseRedirect:
        entered_code = form.cleaned_data.get('code')

        user = CustomUserModel.objects.get(email=self.kwargs.get('email'))

        if entered_code == user.code_from_mail:
            refresh_token = RefreshToken.for_user(user)
            refresh_token['email'] = user.email

            access_token = str(refresh_token.access_token)

            response = super().form_valid(form)

            response.set_cookie(
                key='Authorization',
                value=access_token,
                max_age=36000,
            )

            return response

        else:
            return redirect('user:login-confirm', kwargs={'email': user.email})

    def get_context_data(self, **kwargs) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)

        try:
            user = get_object_or_404(CustomUserModel, email=self.kwargs.get('email'))

        except CustomUserModel.DoesNotExist:
            raise Http404("Пользователь не найден")

        context['title'] = f'Подтверждение почты {user.email}'

        return context

    def get_success_url(self) -> str:
        return reverse_lazy('user:profile')

English_Ekb/user/views/view_profile.py
from typing import Any

from django.http import Http404, HttpRequest, HttpResponse
from django.shortcuts import get_object_or_404, redirect
from django.views.generic import TemplateView

from ..models import CustomUserModel


class UserProfileView(TemplateView):
    template_name = 'user/pages/account.html'
    user: CustomUserModel | None = None

    def dispatch(self, request: HttpRequest, *args, **kwargs) -> HttpResponse:
        current_user = self.request.user

        user = CustomUserModel.objects.filter(email=current_user).first()

        if user is None:
            return redirect('user:login')

        self.user = user

        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs) -> dict[str, Any] | str:
        context = super().get_context_data(**kwargs)

        context['user_profile'] = self.user

        context['title'] = f'Профиль пользователя {self.user.email}'

        return context

English_Ekb/user/views/view_registration.py
from django.http import HttpResponse, HttpRequest, HttpResponseRedirect
from django.urls import reverse
from django.views.generic import CreateView
from django.shortcuts import redirect

from ..forms import RegistrationUserForm


class RegistrationUserView(CreateView):
    form_class = RegistrationUserForm

    template_name = 'user/pages/registration.html'
    extra_context = {'title': 'Регистрация нового пользователя'}

    def dispatch(self, request: HttpRequest, *args, **kwargs) -> HttpResponse:
        if self.request.user:
            return redirect('user:profile')

        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form: RegistrationUserForm) -> HttpResponseRedirect:
        user = form.save()

        user.save()

        return super().form_valid(form)

    def get_success_url(self) -> str:
        return reverse('user:registration-confirm', kwargs={'email': self.object.email})

English_Ekb/user/views/view_shedule.py
from typing import Any

from django.http import HttpResponse, HttpRequest
from django.shortcuts import redirect
from django.views.generic import TemplateView
from django.views.generic.edit import UpdateView

from ..models import CustomUserModel


class ScheduleView(TemplateView):
    template_name = 'user/pages/schedule.html'
    extra_context = {'title': 'Расписание'}

    user: CustomUserModel | None = None

    def dispatch(self, request: HttpRequest, *args, **kwargs) -> HttpResponse:
        session_user = self.request.user
        if session_user is None:
            return redirect('user:login')

        self.user = CustomUserModel.objects.filter(email=session_user).first()

        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs) -> dict[str, Any] | str:
        context = super().get_context_data(**kwargs)

        context['user_profile'] = self.user

        return context

English_Ekb/templates/user/pages/account.html
{% extends 'school/base.html'%}

{% load static %}

{% block head %}
    <title>{% block title %}Личный кабинет{% endblock %}</title>

    <link href="{% static 'styles/index.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'styles/pages/account.css' %}" rel="stylesheet" type="text/css">

{% endblock %}

{% block content %}
    <div class="account-page">
        <div class="profile">
            <h1>Профиль</h1>

            <div class="profile-information">
                <div class="student">
                    <img class="profile-avatar" src="{{ user_profile.avatar.url }}" alt="profile-avatar.svg"/>

                    <div class="student-personal">
                        <p>{{ user_profile.first_name }} {{ user_profile.last_name  }} {{ user_profile.patronymic }}</p>
                        <p>{{ user_profile.phone }}</p>
                        <p>{{ user_profile.email }}</p>
                    </div>
                </div>
            </div>
        </div>

        {% if user_profile.role == 'Student' %}
            <div class="lessons">
                <h1>Мои занятия</h1>

                {% if user_lessons.length > 0 %}
                    <div>

                    </div>

                {% else %}
                    <div class="none-lessons">
                        <p>У вас еще нет занятий.</p>

                        <button class="record-to-lesson">Хочу уроки английского!</button>
                    </div>
                {% endif %}

            </div>
        {% else %}
            <div>
                <table>
                    <thead>
                        <tr>
                            <th></th>
                            <th>Понедельник</th>
                            <th>Вторник</th>
                            <th>Среда</th>
                            <th>Четверг</th>
                            <th>Пятница</th>
                            <th>Суббота</th>
                            <th>Воскресенье</th>
                        </tr>
                    </thead>

                    <tbody>
                        <tr>
                            <th>10.00</th>
                            <td>Иванов</td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>

                        <tr>
                            <th>11.00</th>
                            <td>Бобров</td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>

                        <tr>
                            <th>22.00</th>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td>Петрушки</td>
                        </tr>
                    </tbody>
                </table>

                <div class="button-schedule"><a href="{% url 'user:schedule' %}">Редактировать расписание</a></div>
            </div>
        {% endif %}
    </div>

{% endblock %}

English_Ekb/templates/user/pages/login.html
{% load static %}


<html lang="ru">
    <head>
        <meta charset="utf-8">

        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link href="{% static 'styles/index.css' %}" rel="stylesheet" type="text/css">
        <link href="{% static 'styles/pages/login.css' %}" rel="stylesheet" type="text/css">

        <title>{% block title %}{{ title }}{% endblock %}</title>
    </head>

    <body>
        <main>
            <div class="container">
                {% block content %}
                    <div class="login-page">
                        <img class="background-page" src="{% static 'media/photos/background-user.svg' %}" alt="background.svg"/>

                        <div class="header">
                            <img class="logo" src="{% static 'media/logo/logo-main.svg' %}" alt="logo-main.svg"/>

                            <div class="header-menu">
                                <nav>
                                    <ul class="header-list-menu">
                                        <li>О нас</li>
                                        <li>Уроки</li>
                                        <li>Отзывы</li>
                                        <li>Предподаватели</li>
                                        <li>Блог</li>
                                        <li>Speaking Club</li>
                                        <li>Пособия</li>
                                    </ul>
                                </nav>
                            </div>

                            <div class="header-icons">
                                <a href="#"><img src="{% static 'media/icons/vk-icon.svg' %}" alt="vk-icon.svg"/></a>
                                <a href="#"><img src="{% static 'media/icons/telegram-icon.svg' %}" alt="telegram-icon.svg"/></a>
                                <a href="#"><img src="{% static 'media/icons/instagram-icon.svg' %}" alt="instagram-icon.svg"/></a>
                            </div>

                            <div class="account-buttons">
                                <div class="account-entrance">
                                    <a href="{% url 'user:login' %}">Вход</a>
                                </div>

                                <div class="account-registration">
                                    <a href="{% url 'user:registration' %}">Регистрация</a>
                                </div>
                            </div>
                        </div>

                        <div class="login-content">
                            <div class="login-form">
                                <form method="post">
                                    <p class="header-form">Вход в личный кабинет</p>

                                    {% csrf_token %}

                                    {% if form.non_field_errors %}
                                        <div>
                                            {{ form.non_field_errors }}
                                        </div>
                                    {% endif %}

                                    {% for field in form %}
                                        <p>{{ field }}</p>
                                    {% endfor %}

                                    <div class="login">
                                        <p class="reset-password"><a href="#">Забыли пароль?</a></p>

                                        <button class="login-button" type="submit">Войти</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>

                {% endblock %}
            </div>
        </main>
    </body>
</html>

English_Ekb/templates/user/pages/mail.html
{% load static %}


<html lang="ru">
    <head>
        <meta charset="utf-8">

        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link href="{% static 'styles/index.css' %}" rel="stylesheet" type="text/css">
        <link href="{% static 'styles/pages/mail.css' %}" rel="stylesheet" type="text/css">

        <title>{% block title %}{{ title }}{% endblock %}</title>
    </head>

    <body>
        <main>
            <div class="container">
                {% block content %}
                    <div class="mail-confirm-form">
                        <h1>Подтверждение почты</h1>

                        <div>

                        <form method="post">
                            {% csrf_token %}

                            {% if form.non_field_errors %}
                                <div>
                                    {{ form.non_field_errors }}
                                </div>
                            {% endif %}

                            {% for field in form %}
                                <p>{{ field }}</p>
                            {% endfor %}

                            <div class="confirm">
                                <button type="submit">Зарегистрироваться</button>
                            </div>
                        </form>
                    </div>

                {% endblock %}
            </div>
        </main>
    </body>
</html>

English_Ekb/templates/user/pages/registration.html
{% load static %}


<html lang="ru">
    <head>
        <meta charset="utf-8">

        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link href="{% static 'styles/index.css' %}" rel="stylesheet" type="text/css">
        <link href="{% static 'styles/pages/registration.css' %}" rel="stylesheet" type="text/css">

        <title>{% block title %}{{ title }}{% endblock %}</title>
    </head>

    <body>
        <main>
            <div class="container">
                {% block content %}
                    <div class="registration-page">
                        <img class="logo" src="{% static 'media/logo/logo-main.svg' %}" alt="logo-main.svg"/>

                        <div class="registration-form">
                            <form method="post">
                                {% csrf_token %}

                                {% if form.non_field_errors %}
                                    <div>
                                        {{ form.non_field_errors }}
                                    </div>
                                {% endif %}

                                {% for field in form %}
                                    <div>
                                    <p>{{ field.errors }}</p>
                                    </div>

                                    <p>{{ field }}</p>
                                {% endfor %}

                                <div class="registration">
                                    <a href="#">Забыли пароль?</a>
                                    <button type="submit">Зарегистрироваться</button>
                                </div>
                            </form>
                        </div>

                         <div class="account-buttons">
                             <div class="account-entrance">
                                 <a href="{% url 'user:login' %}">Вход</a>
                             </div>

                             <div class="account-registration">
                                 <a href="{% url 'user:registration' %}">Регистрация</a>
                             </div>
                        </div>
                    </div>

                {% endblock %}
            </div>
        </main>
    </body>
</html>

English_Ekb/templates/user/pages/schedule.html
{% extends 'school/base.html'%}

{% load static %}

{% block head %}
    <title>{% block title %}Расписание{% endblock %}</title>

    <link href="{% static 'styles/index.css' %}" rel="stylesheet" type="text/css">
{% endblock %}

{% block content %}
    <<h1>Расписание</h1>

    <div>
        <table>
            <thead>
            <tr>
                <th>ФИО ученика</th>
                <th>Ссылка на урок</th>
                <th>День недели</th>
                <th>Время</th>
            </tr>
            </thead>

            <tbody>
            <tr>

            </tr>
            <tr>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            </tbody>
        </table>
    </div>
{% endblock content %}